### ISSUE TITLE
Generate contracts' ABIs for the specified release

### ISSUE THREAD

**Issue by pgev** [OpenSTFoundation/openst-contracts#195]
Write a shell script to generate contracts' ABI for the specified release and store in test/data/contract_abi.

```bash
./tools/generate_abi.sh <release-tag>
```

**Comment by schemar** [comment]
Why was this closed? 😕

**Comment by schemar** [comment]
@pgev

**Comment by pgev** [comment]
@schemar I've added a possible solution as a comment to this one: https://github.com/OpenST/openst-contracts/issues/194, as was not sure what is the best way to  handle a multi steps ticket like this.
