### ISSUE TITLE
Repository should provide abstract firewall contract

### ISSUE THREAD

**Issue by schemar** [OpenSTFoundation/openst-contracts#199]
ℹ️ Look at the parent epic for most of the details: #193

## Story

As a consumer of the package
I want to have a re-usable firewall available
Because I want to limit access to some of my rules

## Scenarios

Given that I implement a rule
When I extend the firewall
Then my rule can check for `tx.origin` to be a registered worker with an organisation

## Info

The info is in the epic #193

This ticket is only concerned with:

* Providing the abstract firewall contract that provides the modifier.
* Making sure the firewall can be turned off by the organization.
* Testing.

**Comment by jasonklein** [comment]
@schemar: is this ticket ripe for the backlog? You note the following in the epic:
> Do we really want [a firewall-disabling function modified by `onlyOrganization`] or would we rather replace the firewalled rules with non-firewalled pendants?

**Comment by schemar** [comment]
It can always be changed later if it really has to be changed. Which is unlikely. So we can do it the way Ben instructed last week.

**Comment by schemar** [comment]
I cannot validate with Slither any more, opened a report at https://github.com/crytic/eth-security-toolbox/issues/8
