### ISSUE TITLE
Align across OST contracts the way a signature is presented

### ISSUE THREAD

**Issue by pgev** [OpenSTFoundation/openst-contracts#36]
Different projects (mosaic-contracts, openst-contracts, etc) are presenting the signature differently:
- tuple (r, s, v)
- bytes

In the scope of this ticket, we should align with other projects and have consistent representation.

**Comment by benjaminbollen** [comment]
what is the current interface of signatures in both openst-contracts and mosaic-contracts @gulshanvasnani ?

**Comment by gulshanvasnani** [comment]
1. Current signature interface in mosaic-contracts :- https://github.com/OpenSTFoundation/mosaic-contracts/blob/094fe116cf1fc17fbf10ea698fa24de55a934f68/contracts/gateway/MessageBus.sol#L115  

2. Current Tokenholder.executeRule signature interface in openst-contracts :- https://github.com/OpenSTFoundation/openst-contracts/blob/43fa71e988aa0b660cf7233cb917ef786ffcd05d/contracts/TokenHolder.sol#L274 

**Proposal** :-
 Aligning Tokenholder.executeRule in openst-contracts with mosaic-contracts, the interface at openst-contracts would look as below :-  https://github.com/gulshanvasnani/openst-contracts/blob/103a23bad1fc73a8321af4cd94948c43027403f0/contracts/TokenHolder.sol#L279

Cc: @benjaminbollen

**Comment by benjaminbollen** [comment]
thanks; I want us to keep (v, r, s) explicitly where possible.  In gateway code it was reduced to bytes only because of a limit to put them on the stack.

**Comment by gulshanvasnani** [comment]
@pgev ,should we close this issue ?

**Comment by pgev** [comment]
Closing with resolution wontfix as an agreement is to keep wherever possible the (v, r, s) which is already the case in openst-contracts.
