### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by pgev** [OpenSTFoundation/openst-contracts#43]
- Delete BrandedToken.sol.
- Delete Internal.sol.
- Delete openst-protocol directory. Move the followings to contracts/ directory: mock version of EIP20Token and EIP20Interface.
- Integrate EIP20TokenInterface.sol  with TokenHolder and TokenRules
- Remove Workers, OpsManaged.sol, Owned.sol

**Comment by abhayks1** [comment]
Was thinking to pick up this backlog issue.
May I know reason for removing BrandedToken.sol and Internal.sol out?
cc: @benjaminbollen @pgev @achirala

**Comment by pgev** [comment]
We delete the following contracts from the current repo. However, the contracts would be copied into the new repo (once created).
cc: @abhayks1 @jasonklein

**Comment by abhayks1** [comment]
@pgev Thank you for the update!

**Comment by abhayks1** [comment]
@pgev do we need to keep Workers.sol ?
Will they also be moved to new repo?
