### ISSUE TITLE
TokenHolder must hold only one type of Token  

### ISSUE THREAD

**Issue by achirala** [OpenSTFoundation/openst-contracts#74]

**Comment by abhayks1** [comment]
@achirala Can we get more details on this ticket?
This is the current implementation. At time of TH deployment, a utility token is passed as an argument.
What else expected from this ticket?

**Comment by pgev** [comment]
TokenHolder by design currently holds only a *single* utility token. It's set in construction, and contract has no interface to modify that value.
TokenHolder does not hold OSTPrime also.

/cc @achirala
