### ISSUE TITLE
Update TokenHolder.redeem signature after _facilitator argument is removed from CoGateway.redeem() in mosaic-contracts.

### ISSUE THREAD

**Issue by abhayks1** [OpenSTFoundation/openst-contracts#81]
Current Implementation
https://github.com/OpenSTFoundation/mosaic-contracts/blob/develop/contracts/gateway/EIP20CoGateway.sol#L590

As per discussion with Gateway team, facilitator will be removed from redeem function.
Accordingly CoGatewayRedeemInterface.sol and TokenHolder.redeem function signature needs to be updated.

**Comment by abhayks1** [comment]
It should be taken after below PR is merged:
https://github.com/OpenSTFoundation/mosaic-contracts/pull/517

Tracking Issue: https://github.com/OpenSTFoundation/mosaic-contracts/issues/475

**Comment by pgev** [comment]
Closing the issue, as redeem functionality is going to be updated in #124.
